language: cpp
sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc-7
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'george-edison55-precise-backports']
          packages: ['g++-7', 'cmake', 'cmake-data', 'zlib1g-dev', 'libbz2-dev', 'libboost-dev', 'python', 'python-nose', 'python-jinja2', 'python-pip']
      install: export CXX="g++-7" CC="gcc-7"




script:
  - g++ --version
  - make test
  - ./test
branches:
  only:
  - master

after_success:
  - bash <(curl -s https://codecov.io/bash)
