name: cibuildwheel

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04 ] # , windows-2019, macos-10.15 ]

    steps:
      - uses: actions/checkout@v2

      - name: Build wheels
        uses: joerick/cibuildwheel@v1.10.0

        env:
          CIBW_PROJECT_REQUIRES_PYTHON: ">=3.6"
          CIBW_SKIP: "*-manylinux_i686"
          CIBW_BEFORE_BUILD: |
            yum install bzip2 -y
            pip install --upgrade pip
            pip install cmake
            yum install zlib-devel -y
            yum install centos-release-scl-rh -y
            yum install devtoolset-7-toolchain -y
            yum groupinstall -y "development tools"
            yum install boost-devel -y
            yum install -y zlib-devel bzip2-devel openssl-devel ncurses-devel sqlite-devel readline-devel tk-devel gdbm-devel db4-devel libpcap-devel xz-devel expat-devel
            cmake -Bbuild
            cmake --build build -j4


      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl


  upload_bintray:
    needs: build_wheels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Fetch wheels from artifacts
        id: fetch_artifacts
        uses: actions/download-artifact@v2
        with:
          path: 'wheels'

      - name: Upload wheels to Bintray
        uses: bpicode/github-action-upload-bintray@master
        with:
          file: ./path/to/example-package_1.0_amd64.deb
          api_user: example-user
          api_key: ${{ secrets.BINTRAY_API_KEY }} # An API key can be obtained from the user profile page.
          gpg_passphrase: ${{ secrets.BINTRAY_GPG_PASSPHRASE }} # Optional, for this to work Bintray requires a GPG public/private keypair configured for the repository owner (individual or organization).
          repository_user: mr-eyes
          repository: wheels
          package: kProcessor
          version: '1.0'
#          upload_path: pool/main/m # Typical for debian repository layout
          publish: 1
#          calculate_metadata: true # Schedule metadata calculation after upload
#          deb_distribution: stretch,buster,sid
#          deb_component: main
#          deb_architecture: amd64
